[package]
name = "icondata"
version = "0.1.0"
authors = ["Charles Edward Gagnon"]
edition = "2021"
description = "Icon data from free icon libraries."
readme = "../README.md"
repository = "https://github.com/Carlosted/icondata"
license = "MIT"
keywords = ["leptos", "icons"]
categories = ["web-programming"]
rust-version = "1.60.0"

[dependencies]
icondata_core = "0.0.2"
serde = { workspace = true, optional = true }

icondata_ai = { path = "../icondata_ai", version = "0.0.8" }
icondata_bi = { path = "../icondata_bi", version = "0.0.8" }
icondata_bs = { path = "../icondata_bs", version = "0.0.8" }
icondata_cg = { path = "../icondata_cg", version = "0.0.8" }
icondata_ch = { path = "../icondata_ch", version = "0.0.8" }
icondata_fa = { path = "../icondata_fa", version = "0.0.8" }
icondata_fi = { path = "../icondata_fi", version = "0.0.8" }
icondata_hi = { path = "../icondata_hi", version = "0.0.8" }
icondata_im = { path = "../icondata_im", version = "0.0.8" }
icondata_io = { path = "../icondata_io", version = "0.0.8" }
icondata_lu = { path = "../icondata_lu", version = "0.0.8" }
icondata_oc = { path = "../icondata_oc", version = "0.0.8" }
icondata_ri = { path = "../icondata_ri", version = "0.0.8" }
icondata_si = { path = "../icondata_si", version = "0.0.8" }
icondata_tb = { path = "../icondata_tb", version = "0.0.8" }
icondata_ti = { path = "../icondata_ti", version = "0.0.8" }
icondata_vs = { path = "../icondata_vs", version = "0.0.8" }
icondata_wi = { path = "../icondata_wi", version = "0.0.8" }
[features]
strum = [
"icondata_ai/strum",
"icondata_bi/strum",
"icondata_bs/strum",
"icondata_cg/strum",
"icondata_ch/strum",
"icondata_fa/strum",
"icondata_fi/strum",
"icondata_hi/strum",
"icondata_im/strum",
"icondata_io/strum",
"icondata_lu/strum",
"icondata_oc/strum",
"icondata_ri/strum",
"icondata_si/strum",
"icondata_tb/strum",
"icondata_ti/strum",
"icondata_vs/strum",
"icondata_wi/strum",
]
serde = [
"dep:serde",
"icondata_ai/serde",
"icondata_bi/serde",
"icondata_bs/serde",
"icondata_cg/serde",
"icondata_ch/serde",
"icondata_fa/serde",
"icondata_fi/serde",
"icondata_hi/serde",
"icondata_im/serde",
"icondata_io/serde",
"icondata_lu/serde",
"icondata_oc/serde",
"icondata_ri/serde",
"icondata_si/serde",
"icondata_tb/serde",
"icondata_ti/serde",
"icondata_vs/serde",
"icondata_wi/serde",
]